### ISSUE TITLE
Package dependencies and compiler issues 

### ISSUE THREAD

**Issue by hasansuleman1** [Unity-Technologies/megacity-metro#6]
My unity version 2022.3

I tried reinstalling the following packages to the latest available packages :

Entities Graphics
NetCode
Unity Physics
Render pipelines.universal
Visual effect graph
<img width="1473" alt="Screenshot 2024-03-14 at 1 20 14 PM" src="https://github.com/Unity-Technologies/megacity-metro/assets/13772642/d49b54c7-aa1e-489d-b5ac-c38f23f24938">

I even tried commenting out some code that was causing compilation errors. 
<img width="517" alt="Screenshot 2024-03-14 at 1 13 16 PM" src="https://github.com/Unity-Technologies/megacity-metro/assets/13772642/eb4aad9b-17f5-40c3-a257-c03654475d54">

**Comment by sql4088** [comment]
@hasansuleman1 You have to Clone the project using Git LTS.  That will solve your issue.  You cannot download this project as a zip because of GIT LTS compression.
